namespace GW2Api.NET.V1.Items.Dto.ItemTypes.UpgradeComponent
{
    public enum UpgradeComponentFlag
    {
        HeavyArmor,
        LightArmor,
        MediumArmor,
        Axe,
        Dagger,
        Focus,
        Greatsword,
        Hammer,
        Harpoon,
        LongBow,
        Mace,
        Pistol,
        Rifle,
        Scepter,
        Shield,
        ShortBow,
        Speargun,
        Staff,
        Sword,
        Torch,
        Trident,
        Warhorn,
        Trinket
    }
}
